//! AUTO-GENERATED by tools/generate_door_api_fixture.py — DO NOT HAND-EDIT.
//! Regenerate: python3 tools/generate_door_api_fixture.py  (from zig_iroh/)
//!
//! Fork-isolation amendment A4: the door API FIXTURE. Compiled per product
//! against that product's door; FAILS the build unless every entry of the S0
//! compatibility manifest (transport-surface-manifest.yaml, 107 entries) is
//! present — transport methods with full door-typed signature equality
//! (24 full-signature checks, 83 presence/member/arity checks).
//! Independent of shared/door_surface_lock.zig (that lock rejects additions;
//! this fixture rejects omissions and signature drift).

const std = @import("std");
const door = @import("transport");
const build_options = @import("build_options");

fn errorSetHas(comptime E: type, comptime name: []const u8) bool {
    const info = @typeInfo(E).error_set orelse return false;
    for (info) |err| {
        if (std.mem.eql(u8, err.name, name)) return true;
    }
    return false;
}

comptime {
    if (!@hasDecl(door, "NodeId")) @compileError("A4 manifest: missing transport.NodeId");
    if (@TypeOf(door.NodeId) != type) @compileError("A4 manifest: transport.NodeId is not a type");
    if (!@hasDecl(door, "EndpointAddr")) @compileError("A4 manifest: missing transport.EndpointAddr");
    if (@TypeOf(door.EndpointAddr) != type) @compileError("A4 manifest: transport.EndpointAddr is not a type");
    if (!@hasDecl(door, "NodeAddr")) @compileError("A4 manifest: missing transport.NodeAddr");
    if (@TypeOf(door.NodeAddr) != type) @compileError("A4 manifest: transport.NodeAddr is not a type");
    if (!@hasDecl(door, "TransportAddr")) @compileError("A4 manifest: missing transport.TransportAddr");
    if (@TypeOf(door.TransportAddr) != type) @compileError("A4 manifest: transport.TransportAddr is not a type");
    if (!@hasDecl(door, "RelayUrl")) @compileError("A4 manifest: missing transport.RelayUrl");
    if (@TypeOf(door.RelayUrl) != type) @compileError("A4 manifest: transport.RelayUrl is not a type");
    if (!@hasDecl(door, "CustomAddr")) @compileError("A4 manifest: missing transport.CustomAddr");
    if (@TypeOf(door.CustomAddr) != type) @compileError("A4 manifest: transport.CustomAddr is not a type");
    if (!@hasDecl(door, "Error")) @compileError("A4 manifest: missing transport.Error");
    if (@TypeOf(door.Error) != type) @compileError("A4 manifest: transport.Error is not a type");
    if (!errorSetHas(door.Error, "ConnectionLost")) @compileError("A4 manifest: transport.Error.ConnectionLost missing");
    if (!errorSetHas(door.Error, "StreamReset")) @compileError("A4 manifest: transport.Error.StreamReset missing");
    if (!errorSetHas(door.Error, "Timeout")) @compileError("A4 manifest: transport.Error.Timeout missing");
    if (!errorSetHas(door.Error, "NotConnected")) @compileError("A4 manifest: transport.Error.NotConnected missing");
    if (!errorSetHas(door.Error, "OutOfMemory")) @compileError("A4 manifest: transport.Error.OutOfMemory missing");
    if (!@hasDecl(door, "CongestionController")) @compileError("A4 manifest: missing transport.CongestionController");
    if (@TypeOf(door.CongestionController) != type) @compileError("A4 manifest: transport.CongestionController is not a type");
    if (!@hasField(door.CongestionController, "unknown")) @compileError("A4 manifest: transport.CongestionController lost enum member unknown");
    if (!@hasField(door.CongestionController, "new_reno")) @compileError("A4 manifest: transport.CongestionController lost enum member new_reno");
    if (!@hasField(door.CongestionController, "cubic")) @compileError("A4 manifest: transport.CongestionController lost enum member cubic");
    if (!@hasField(door.CongestionController, "bbr3")) @compileError("A4 manifest: transport.CongestionController lost enum member bbr3");
    if (!@hasDecl(door, "ConnectionStats")) @compileError("A4 manifest: missing transport.ConnectionStats");
    if (@TypeOf(door.ConnectionStats) != type) @compileError("A4 manifest: transport.ConnectionStats is not a type");
    if (!@hasField(door.ConnectionStats, "smoothed_rtt_ns")) @compileError("A4 manifest: missing field transport.ConnectionStats.smoothed_rtt_ns");
    if (!@hasField(door.ConnectionStats, "latest_rtt_ns")) @compileError("A4 manifest: missing field transport.ConnectionStats.latest_rtt_ns");
    if (!@hasField(door.ConnectionStats, "path_mtu")) @compileError("A4 manifest: missing field transport.ConnectionStats.path_mtu");
    if (!@hasField(door.ConnectionStats, "congestion_window")) @compileError("A4 manifest: missing field transport.ConnectionStats.congestion_window");
    if (!@hasField(door.ConnectionStats, "bytes_in_flight")) @compileError("A4 manifest: missing field transport.ConnectionStats.bytes_in_flight");
    if (!@hasField(door.ConnectionStats, "congestion_controller")) @compileError("A4 manifest: missing field transport.ConnectionStats.congestion_controller");
    if (!@hasField(door.ConnectionStats, "app_limited_acks")) @compileError("A4 manifest: missing field transport.ConnectionStats.app_limited_acks");
    if (!@hasField(door.ConnectionStats, "spurious_congestion_events")) @compileError("A4 manifest: missing field transport.ConnectionStats.spurious_congestion_events");
    if (!@hasField(door.ConnectionStats, "abandoned_recv_bytes")) @compileError("A4 manifest: missing field transport.ConnectionStats.abandoned_recv_bytes");
    if (!@hasDecl(door, "SendStream")) @compileError("A4 manifest: missing transport.SendStream");
    if (@TypeOf(door.SendStream) != type) @compileError("A4 manifest: transport.SendStream is not a type");
    if (!@hasDecl(door, "RecvStream")) @compileError("A4 manifest: missing transport.RecvStream");
    if (@TypeOf(door.RecvStream) != type) @compileError("A4 manifest: transport.RecvStream is not a type");
    if (!@hasDecl(door, "BiStream")) @compileError("A4 manifest: missing transport.BiStream");
    if (@TypeOf(door.BiStream) != type) @compileError("A4 manifest: transport.BiStream is not a type");
    if (!@hasDecl(door, "Connection")) @compileError("A4 manifest: missing transport.Connection");
    if (@TypeOf(door.Connection) != type) @compileError("A4 manifest: transport.Connection is not a type");
    if (!@hasDecl(door, "Transport")) @compileError("A4 manifest: missing transport.Transport");
    if (@TypeOf(door.Transport) != type) @compileError("A4 manifest: transport.Transport is not a type");
    if (!@hasDecl(door.SendStream, "writer")) @compileError("A4 manifest: missing transport.SendStream.writer");
    if (@TypeOf(@field(door.SendStream, "writer")) != fn (door.SendStream) *std.Io.Writer) @compileError("A4 manifest: signature drift on transport.SendStream.writer");
    if (!@hasDecl(door.SendStream, "pendingFailure")) @compileError("A4 manifest: missing transport.SendStream.pendingFailure");
    if (@TypeOf(@field(door.SendStream, "pendingFailure")) != fn (door.SendStream) ?door.Error) @compileError("A4 manifest: signature drift on transport.SendStream.pendingFailure");
    if (!@hasDecl(door.SendStream, "resetCode")) @compileError("A4 manifest: missing transport.SendStream.resetCode");
    if (@TypeOf(@field(door.SendStream, "resetCode")) != fn (door.SendStream) ?u64) @compileError("A4 manifest: signature drift on transport.SendStream.resetCode");
    if (!@hasDecl(door.SendStream, "flush")) @compileError("A4 manifest: missing transport.SendStream.flush");
    if (@TypeOf(@field(door.SendStream, "flush")) != fn (door.SendStream) door.Error!void) @compileError("A4 manifest: signature drift on transport.SendStream.flush");
    if (!@hasDecl(door.SendStream, "finish")) @compileError("A4 manifest: missing transport.SendStream.finish");
    if (@TypeOf(@field(door.SendStream, "finish")) != fn (door.SendStream) door.Error!void) @compileError("A4 manifest: signature drift on transport.SendStream.finish");
    if (!@hasDecl(door.SendStream, "reset")) @compileError("A4 manifest: missing transport.SendStream.reset");
    if (@TypeOf(@field(door.SendStream, "reset")) != fn (door.SendStream) void) @compileError("A4 manifest: signature drift on transport.SendStream.reset");
    if (!@hasDecl(door.SendStream, "resetWithCode")) @compileError("A4 manifest: missing transport.SendStream.resetWithCode");
    if (@TypeOf(@field(door.SendStream, "resetWithCode")) != fn (door.SendStream, u64) void) @compileError("A4 manifest: signature drift on transport.SendStream.resetWithCode");
    if (!@hasDecl(door.RecvStream, "reader")) @compileError("A4 manifest: missing transport.RecvStream.reader");
    if (@TypeOf(@field(door.RecvStream, "reader")) != fn (door.RecvStream) *std.Io.Reader) @compileError("A4 manifest: signature drift on transport.RecvStream.reader");
    if (!@hasDecl(door.RecvStream, "stop")) @compileError("A4 manifest: missing transport.RecvStream.stop");
    if (@TypeOf(@field(door.RecvStream, "stop")) != fn (door.RecvStream) door.Error!void) @compileError("A4 manifest: signature drift on transport.RecvStream.stop");
    if (!@hasDecl(door.RecvStream, "resetCode")) @compileError("A4 manifest: missing transport.RecvStream.resetCode");
    if (@TypeOf(@field(door.RecvStream, "resetCode")) != fn (door.RecvStream) ?u64) @compileError("A4 manifest: signature drift on transport.RecvStream.resetCode");
    if (!@hasDecl(door.Connection, "openBi")) @compileError("A4 manifest: missing transport.Connection.openBi");
    if (@TypeOf(@field(door.Connection, "openBi")) != fn (door.Connection) door.Error!door.BiStream) @compileError("A4 manifest: signature drift on transport.Connection.openBi");
    if (!@hasDecl(door.Connection, "acceptBi")) @compileError("A4 manifest: missing transport.Connection.acceptBi");
    if (@TypeOf(@field(door.Connection, "acceptBi")) != fn (door.Connection) door.Error!door.BiStream) @compileError("A4 manifest: signature drift on transport.Connection.acceptBi");
    if (!@hasDecl(door.Connection, "openUni")) @compileError("A4 manifest: missing transport.Connection.openUni");
    if (@TypeOf(@field(door.Connection, "openUni")) != fn (door.Connection) door.Error!door.SendStream) @compileError("A4 manifest: signature drift on transport.Connection.openUni");
    if (!@hasDecl(door.Connection, "acceptUni")) @compileError("A4 manifest: missing transport.Connection.acceptUni");
    if (@TypeOf(@field(door.Connection, "acceptUni")) != fn (door.Connection) door.Error!door.RecvStream) @compileError("A4 manifest: signature drift on transport.Connection.acceptUni");
    if (!@hasDecl(door.Connection, "remoteNodeId")) @compileError("A4 manifest: missing transport.Connection.remoteNodeId");
    if (@TypeOf(@field(door.Connection, "remoteNodeId")) != fn (door.Connection) door.NodeId) @compileError("A4 manifest: signature drift on transport.Connection.remoteNodeId");
    if (!@hasDecl(door.Connection, "alpn")) @compileError("A4 manifest: missing transport.Connection.alpn");
    if (@TypeOf(@field(door.Connection, "alpn")) != fn (door.Connection) ?[]const u8) @compileError("A4 manifest: signature drift on transport.Connection.alpn");
    if (!@hasDecl(door.Connection, "remoteAddress")) @compileError("A4 manifest: missing transport.Connection.remoteAddress");
    if (@TypeOf(@field(door.Connection, "remoteAddress")) != fn (door.Connection) ?std.Io.net.IpAddress) @compileError("A4 manifest: signature drift on transport.Connection.remoteAddress");
    if (!@hasDecl(door.Connection, "close")) @compileError("A4 manifest: missing transport.Connection.close");
    if (@TypeOf(@field(door.Connection, "close")) != fn (door.Connection) void) @compileError("A4 manifest: signature drift on transport.Connection.close");
    if (!@hasDecl(door.Connection, "io")) @compileError("A4 manifest: missing transport.Connection.io");
    if (@TypeOf(@field(door.Connection, "io")) != fn (door.Connection) std.Io) @compileError("A4 manifest: signature drift on transport.Connection.io");
    if (!@hasDecl(door.Connection, "stats")) @compileError("A4 manifest: missing transport.Connection.stats");
    if (@TypeOf(@field(door.Connection, "stats")) != fn (door.Connection) door.ConnectionStats) @compileError("A4 manifest: signature drift on transport.Connection.stats");
    if (!@hasDecl(door.Transport, "connect")) @compileError("A4 manifest: missing transport.Transport.connect");
    if (@TypeOf(@field(door.Transport, "connect")) != fn (door.Transport, door.NodeAddr) door.Error!door.Connection) @compileError("A4 manifest: signature drift on transport.Transport.connect");
    if (!@hasDecl(door.Transport, "accept")) @compileError("A4 manifest: missing transport.Transport.accept");
    if (@TypeOf(@field(door.Transport, "accept")) != fn (door.Transport) door.Error!door.Connection) @compileError("A4 manifest: signature drift on transport.Transport.accept");
    if (!@hasDecl(door.Transport, "localNodeId")) @compileError("A4 manifest: missing transport.Transport.localNodeId");
    if (@TypeOf(@field(door.Transport, "localNodeId")) != fn (door.Transport) door.NodeId) @compileError("A4 manifest: signature drift on transport.Transport.localNodeId");
    if (!@hasDecl(door.Transport, "io")) @compileError("A4 manifest: missing transport.Transport.io");
    if (@TypeOf(@field(door.Transport, "io")) != fn (door.Transport) std.Io) @compileError("A4 manifest: signature drift on transport.Transport.io");
    if (!@hasDecl(door.factory, "SelectedPath")) @compileError("A4 manifest: missing factory.SelectedPath");
    if (@TypeOf(door.factory.SelectedPath) != type) @compileError("A4 manifest: factory.SelectedPath is not a type");
    if (!@hasDecl(door.factory, "Engine")) @compileError("A4 manifest: missing factory.Engine");
    if (@TypeOf(door.factory.Engine) != type) @compileError("A4 manifest: factory.Engine is not a type");
    if (!@hasField(door.factory.Engine, "picoquic")) @compileError("A4 manifest: factory.Engine lost enum member picoquic");
    if (!@hasField(door.factory.Engine, "noq")) @compileError("A4 manifest: factory.Engine lost enum member noq");
    if (!@hasDecl(door.factory, "TlsBackend")) @compileError("A4 manifest: missing factory.TlsBackend");
    if (@TypeOf(door.factory.TlsBackend) != type) @compileError("A4 manifest: factory.TlsBackend is not a type");
    if (!@hasDecl(door.factory, "CongestionKind")) @compileError("A4 manifest: missing factory.CongestionKind");
    if (@TypeOf(door.factory.CongestionKind) != type) @compileError("A4 manifest: factory.CongestionKind is not a type");
    if (!@hasDecl(door.factory, "InboundUniEvent")) @compileError("A4 manifest: missing factory.InboundUniEvent");
    if (@TypeOf(door.factory.InboundUniEvent) != type) @compileError("A4 manifest: factory.InboundUniEvent is not a type");
    if (!@hasDecl(door.factory, "DatagramError")) @compileError("A4 manifest: missing factory.DatagramError");
    if (@TypeOf(door.factory.DatagramError) != type) @compileError("A4 manifest: factory.DatagramError is not a type");
    if (!@hasDecl(door.factory, "Options")) @compileError("A4 manifest: missing factory.Options");
    if (@TypeOf(door.factory.Options) != type) @compileError("A4 manifest: factory.Options is not a type");
    if (!@hasField(door.factory.Options, "bind_address")) @compileError("A4 manifest: missing field factory.Options.bind_address");
    if (!@hasField(door.factory.Options, "expected_peer")) @compileError("A4 manifest: missing field factory.Options.expected_peer");
    if (!@hasField(door.factory.Options, "accept_unknown_peer")) @compileError("A4 manifest: missing field factory.Options.accept_unknown_peer");
    if (!@hasField(door.factory.Options, "certificate_public_key_override")) @compileError("A4 manifest: missing field factory.Options.certificate_public_key_override");
    if (!@hasField(door.factory.Options, "certificate_der_override")) @compileError("A4 manifest: missing field factory.Options.certificate_der_override");
    if (!@hasField(door.factory.Options, "retry")) @compileError("A4 manifest: missing field factory.Options.retry");
    if (!@hasField(door.factory.Options, "tls_backend")) @compileError("A4 manifest: missing field factory.Options.tls_backend");
    if (!@hasField(door.factory.Options, "congestion_kind")) @compileError("A4 manifest: missing field factory.Options.congestion_kind");
    if (!@hasField(door.factory.Options, "certificate_request_signature_algorithms")) @compileError("A4 manifest: missing field factory.Options.certificate_request_signature_algorithms");
    if (!@hasField(door.factory.Options, "zero_rtt")) @compileError("A4 manifest: missing field factory.Options.zero_rtt");
    if (!@hasField(door.factory.Options, "background_pump")) @compileError("A4 manifest: missing field factory.Options.background_pump");
    if (!@hasDecl(door.factory, "AnyEndpoint")) @compileError("A4 manifest: missing factory.AnyEndpoint");
    if (@TypeOf(door.factory.AnyEndpoint) != type) @compileError("A4 manifest: factory.AnyEndpoint is not a type");
    if (!@hasDecl(door.factory.AnyEndpoint, "engine")) @compileError("A4 manifest: missing factory.AnyEndpoint.engine");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "engine"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.engine is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "engine"))).@"fn".params.len != 1) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.engine");
    if (!@hasDecl(door.factory.AnyEndpoint, "transport")) @compileError("A4 manifest: missing factory.AnyEndpoint.transport");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "transport"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.transport is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "transport"))).@"fn".params.len != 1) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.transport");
    if (!@hasDecl(door.factory.AnyEndpoint, "localAddress")) @compileError("A4 manifest: missing factory.AnyEndpoint.localAddress");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "localAddress"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.localAddress is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "localAddress"))).@"fn".params.len != 1) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.localAddress");
    if (!@hasDecl(door.factory.AnyEndpoint, "tlsBackend")) @compileError("A4 manifest: missing factory.AnyEndpoint.tlsBackend");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "tlsBackend"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.tlsBackend is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "tlsBackend"))).@"fn".params.len != 1) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.tlsBackend");
    if (!@hasDecl(door.factory.AnyEndpoint, "tryAcceptReady")) @compileError("A4 manifest: missing factory.AnyEndpoint.tryAcceptReady");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "tryAcceptReady"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.tryAcceptReady is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "tryAcceptReady"))).@"fn".params.len != 1) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.tryAcceptReady");
    if (!@hasDecl(door.factory.AnyEndpoint, "tryAcceptReadyZeroRtt")) @compileError("A4 manifest: missing factory.AnyEndpoint.tryAcceptReadyZeroRtt");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "tryAcceptReadyZeroRtt"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.tryAcceptReadyZeroRtt is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "tryAcceptReadyZeroRtt"))).@"fn".params.len != 1) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.tryAcceptReadyZeroRtt");
    if (!@hasDecl(door.factory.AnyEndpoint, "canOfferZeroRtt")) @compileError("A4 manifest: missing factory.AnyEndpoint.canOfferZeroRtt");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "canOfferZeroRtt"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.canOfferZeroRtt is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "canOfferZeroRtt"))).@"fn".params.len != 2) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.canOfferZeroRtt");
    if (!@hasDecl(door.factory.AnyEndpoint, "connectZeroRtt")) @compileError("A4 manifest: missing factory.AnyEndpoint.connectZeroRtt");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "connectZeroRtt"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.connectZeroRtt is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "connectZeroRtt"))).@"fn".params.len != 3) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.connectZeroRtt");
    if (!@hasDecl(door.factory.AnyEndpoint, "SetAlpnsError")) @compileError("A4 manifest: missing decl factory.AnyEndpoint.SetAlpnsError");
    if (!@hasDecl(door.factory.AnyEndpoint, "setAlpns")) @compileError("A4 manifest: missing factory.AnyEndpoint.setAlpns");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "setAlpns"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.setAlpns is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "setAlpns"))).@"fn".params.len != 2) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.setAlpns");
    if (!@hasDecl(door.factory.AnyEndpoint, "pollOnce")) @compileError("A4 manifest: missing factory.AnyEndpoint.pollOnce");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "pollOnce"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.pollOnce is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "pollOnce"))).@"fn".params.len != 1) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.pollOnce");
    if (!@hasDecl(door.factory.AnyEndpoint, "connectionIsClosed")) @compileError("A4 manifest: missing factory.AnyEndpoint.connectionIsClosed");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "connectionIsClosed"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.connectionIsClosed is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "connectionIsClosed"))).@"fn".params.len != 2) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.connectionIsClosed");
    if (!@hasDecl(door.factory.AnyEndpoint, "connectionTryAcceptBi")) @compileError("A4 manifest: missing factory.AnyEndpoint.connectionTryAcceptBi");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "connectionTryAcceptBi"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.connectionTryAcceptBi is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "connectionTryAcceptBi"))).@"fn".params.len != 2) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.connectionTryAcceptBi");
    if (!@hasDecl(door.factory.AnyEndpoint, "sendQueueFinish")) @compileError("A4 manifest: missing factory.AnyEndpoint.sendQueueFinish");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "sendQueueFinish"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.sendQueueFinish is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "sendQueueFinish"))).@"fn".params.len != 2) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.sendQueueFinish");
    if (!@hasDecl(door.factory.AnyEndpoint, "sendPollFinishComplete")) @compileError("A4 manifest: missing factory.AnyEndpoint.sendPollFinishComplete");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "sendPollFinishComplete"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.sendPollFinishComplete is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "sendPollFinishComplete"))).@"fn".params.len != 2) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.sendPollFinishComplete");
    if (!@hasDecl(door.factory.AnyEndpoint, "nextInboundUniEvent")) @compileError("A4 manifest: missing factory.AnyEndpoint.nextInboundUniEvent");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "nextInboundUniEvent"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.nextInboundUniEvent is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "nextInboundUniEvent"))).@"fn".params.len != 3) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.nextInboundUniEvent");
    if (!@hasDecl(door.factory.AnyEndpoint, "closeAllConnections")) @compileError("A4 manifest: missing factory.AnyEndpoint.closeAllConnections");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "closeAllConnections"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.closeAllConnections is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "closeAllConnections"))).@"fn".params.len != 1) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.closeAllConnections");
    if (!@hasDecl(door.factory.AnyEndpoint, "deinit")) @compileError("A4 manifest: missing factory.AnyEndpoint.deinit");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "deinit"))) != .@"fn") @compileError("A4 manifest: factory.AnyEndpoint.deinit is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory.AnyEndpoint, "deinit"))).@"fn".params.len != 1) @compileError("A4 manifest: arity drift on factory.AnyEndpoint.deinit");
    if (!@hasDecl(door.factory.AnyEndpoint, "noqPtr")) @compileError("A4 manifest: missing factory.AnyEndpoint.noqPtr");
    if (!@hasDecl(door.factory.AnyEndpoint, "picoquicPtr")) @compileError("A4 manifest: missing factory.AnyEndpoint.picoquicPtr");
    if (!@hasField(door.factory.AnyEndpoint, "inner")) @compileError("A4 manifest: missing field factory.AnyEndpoint.inner");
    if (!@hasDecl(door.factory, "setNoqRelay")) @compileError("A4 manifest: missing factory.setNoqRelay");
    if (@typeInfo(@TypeOf(@field(door.factory, "setNoqRelay"))) != .@"fn") @compileError("A4 manifest: factory.setNoqRelay is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory, "setNoqRelay"))).@"fn".params.len != 2) @compileError("A4 manifest: arity drift on factory.setNoqRelay");
    if (!@hasDecl(door.factory, "IncomingFilterOutcome")) @compileError("A4 manifest: missing factory.IncomingFilterOutcome");
    if (@TypeOf(door.factory.IncomingFilterOutcome) != type) @compileError("A4 manifest: factory.IncomingFilterOutcome is not a type");
    if (!@hasDecl(door.factory, "IncomingInfo")) @compileError("A4 manifest: missing factory.IncomingInfo");
    if (@TypeOf(door.factory.IncomingInfo) != type) @compileError("A4 manifest: factory.IncomingInfo is not a type");
    if (!@hasDecl(door.factory, "IncomingFilter")) @compileError("A4 manifest: missing factory.IncomingFilter");
    if (@TypeOf(door.factory.IncomingFilter) != type) @compileError("A4 manifest: factory.IncomingFilter is not a type");
    if (!@hasDecl(door.factory, "setNoqIncomingFilter")) @compileError("A4 manifest: missing factory.setNoqIncomingFilter");
    if (@typeInfo(@TypeOf(@field(door.factory, "setNoqIncomingFilter"))) != .@"fn") @compileError("A4 manifest: factory.setNoqIncomingFilter is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory, "setNoqIncomingFilter"))).@"fn".params.len != 2) @compileError("A4 manifest: arity drift on factory.setNoqIncomingFilter");
    if (!@hasDecl(door.factory, "RelayAttachError")) @compileError("A4 manifest: missing factory.RelayAttachError");
    if (@TypeOf(door.factory.RelayAttachError) != type) @compileError("A4 manifest: factory.RelayAttachError is not a type");
    if (!@hasDecl(door.factory, "setPicoquicRelay")) @compileError("A4 manifest: missing factory.setPicoquicRelay");
    if (@typeInfo(@TypeOf(@field(door.factory, "setPicoquicRelay"))) != .@"fn") @compileError("A4 manifest: factory.setPicoquicRelay is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory, "setPicoquicRelay"))).@"fn".params.len != 2) @compileError("A4 manifest: arity drift on factory.setPicoquicRelay");
    if (!@hasDecl(door.factory, "productEngine")) @compileError("A4 manifest: missing factory.productEngine");
    if (@typeInfo(@TypeOf(@field(door.factory, "productEngine"))) != .@"fn") @compileError("A4 manifest: factory.productEngine is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory, "productEngine"))).@"fn".params.len != 0) @compileError("A4 manifest: arity drift on factory.productEngine");
    if (!@hasDecl(door.factory, "productTlsBackend")) @compileError("A4 manifest: missing factory.productTlsBackend");
    if (@typeInfo(@TypeOf(@field(door.factory, "productTlsBackend"))) != .@"fn") @compileError("A4 manifest: factory.productTlsBackend is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory, "productTlsBackend"))).@"fn".params.len != 0) @compileError("A4 manifest: arity drift on factory.productTlsBackend");
    if (!@hasDecl(door.factory, "createForProduct")) @compileError("A4 manifest: missing factory.createForProduct");
    if (@typeInfo(@TypeOf(@field(door.factory, "createForProduct"))) != .@"fn") @compileError("A4 manifest: factory.createForProduct is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory, "createForProduct"))).@"fn".params.len != 5) @compileError("A4 manifest: arity drift on factory.createForProduct");
    if (!@hasDecl(door.factory, "create")) @compileError("A4 manifest: missing factory.create");
    if (@typeInfo(@TypeOf(@field(door.factory, "create"))) != .@"fn") @compileError("A4 manifest: factory.create is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory, "create"))).@"fn".params.len != 6) @compileError("A4 manifest: arity drift on factory.create");
    if (!@hasDecl(door.factory, "connectionSendDatagram")) @compileError("A4 manifest: missing factory.connectionSendDatagram");
    if (@typeInfo(@TypeOf(@field(door.factory, "connectionSendDatagram"))) != .@"fn") @compileError("A4 manifest: factory.connectionSendDatagram is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory, "connectionSendDatagram"))).@"fn".params.len != 3) @compileError("A4 manifest: arity drift on factory.connectionSendDatagram");
    if (!@hasDecl(door.factory, "connectionReadDatagram")) @compileError("A4 manifest: missing factory.connectionReadDatagram");
    if (@typeInfo(@TypeOf(@field(door.factory, "connectionReadDatagram"))) != .@"fn") @compileError("A4 manifest: factory.connectionReadDatagram is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory, "connectionReadDatagram"))).@"fn".params.len != 4) @compileError("A4 manifest: arity drift on factory.connectionReadDatagram");
    if (!@hasDecl(door.factory, "connectionMaxDatagramSize")) @compileError("A4 manifest: missing factory.connectionMaxDatagramSize");
    if (@typeInfo(@TypeOf(@field(door.factory, "connectionMaxDatagramSize"))) != .@"fn") @compileError("A4 manifest: factory.connectionMaxDatagramSize is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory, "connectionMaxDatagramSize"))).@"fn".params.len != 2) @compileError("A4 manifest: arity drift on factory.connectionMaxDatagramSize");
    if (!@hasDecl(door.factory, "connectionSelectedPath")) @compileError("A4 manifest: missing factory.connectionSelectedPath");
    if (@typeInfo(@TypeOf(@field(door.factory, "connectionSelectedPath"))) != .@"fn") @compileError("A4 manifest: factory.connectionSelectedPath is not a fn");
    if (@typeInfo(@TypeOf(@field(door.factory, "connectionSelectedPath"))).@"fn".params.len != 2) @compileError("A4 manifest: arity drift on factory.connectionSelectedPath");
}

test "A4 per-engine behavior table: the ACTIVE product's engine + TLS backend selection" {
    // Explicit behavior table (not an ellipsis): the door's factory must
    // resolve to the engine/TLS pair the product declares via build_options.
    const expected_engine: door.factory.Engine = if (build_options.noq) .noq else .picoquic;
    try std.testing.expectEqual(expected_engine, door.factory.productEngine());
    const expected_tls: door.factory.TlsBackend = if (build_options.zigtls) .zigtls else .picotls;
    try std.testing.expectEqual(expected_tls, door.factory.productTlsBackend());
    // Capability entry points exist on EVERY product's door (per-engine
    // runtime behavior — pico: null/false shims; noq: live paths — is graded
    // by the real-peer interop matrix, not unit fixtures).
    comptime {
        for ([_][]const u8{ "tryAcceptReadyZeroRtt", "canOfferZeroRtt", "connectZeroRtt", "nextInboundUniEvent" }) |cap| {
            if (!@hasDecl(door.factory.AnyEndpoint, cap)) @compileError("A4 caps: AnyEndpoint lost " ++ cap);
        }
        for ([_][]const u8{ "connectionSendDatagram", "connectionReadDatagram", "connectionMaxDatagramSize", "setNoqIncomingFilter", "setNoqRelay", "setPicoquicRelay" }) |cap| {
            if (!@hasDecl(door.factory, cap)) @compileError("A4 caps: factory lost " ++ cap);
        }
    }
}
